// Code generated by github.com/acomagu/optional. DO NOT EDIT.

package main

// T
type OptionalT struct {
	v   *T
	has bool
}

func NoneT() OptionalT {
	return OptionalT{}
}

func SomeT(v *T) OptionalT {
	return OptionalT{
		v:   v,
		has: true,
	}
}

func (o OptionalT) Get() (*T, bool) {
	return o.v, o.has
}
