version: 2
jobs:
  build:
    docker:
      - image: circleci/golang

    working_directory: /go/src/github.com/acomagu/optional
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -v ./...
